port: 7880
bind_addresses:
  - 0.0.0.0

keys:
  devkey: secret

redis:
  address: localhost:6379
  password: 
  db: 0

room:
  auto_create: 
  empty_timeout: 
  max_participants: 

logging:
  level: 

turn:
  enabled: 
  domain: 
  external_tls_port: 
  external_udp_port: 
